language: node_js
node_js:
  - "8.2.1"

install:
  - npm install

before_script:
  - node --version
  - npm --version

script:
  - node_modules/.bin/newman run tests/my.json

deploy:
  provider: heroku
  api_key: $MY_SECRET_ENV
  app: testnfg
