language: node_js
node_js:
  - "10.15.3"
services: 
  - docker 
install:
  - npm install
before_script:
  - node --version
  - npm --version
  

script:
  - docker build . -t no4good597/apps:v1
  - docker login -u $SECRET_CLOUD_LOGIN -p $SECRET_CLOUD_PASS
  - docker push no4good597/apps:v1
